library(conflicted)
## library(dotenv)
library(drake)
library(dplyr)
library(magrittr)
library(readr)
library(tidyr)
library(jsonlite)
library(purrr)
library(stringr)
library(lubridate)
library(tibble)
library(DataPackageR)
library(ggplot2)
library(shirthesis)
library(webshot)
library(slider)
library(janitor)
library(jaysire)
library(htmltools)
library(js)
library(magic)
library(anecdotes1)
library(printy)
library(faux)
library(forcats)
library(papaja)
library(afex)
library(broom)
library(emmeans)
library(binom)

conflict_prefer("filter", "dplyr")
conflict_prefer("flatten", "purrr")
